version: '3.9'
volumes:
  squad_data:

services:
  squad-server:
    image: cm2network/squad
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - squad_data:/home/steam/squad-dedicated/

    environment:
      - PORT=7787
      - BEACONPORT=15000  
      - QUERYPORT=27165
      - RCONPORT=21114
      - FIXEDMAXPLAYERS=100

    ports:
      - 7787:7787/tcp
      - 7788:7788/tcp
      - 15000:15000/tcp
      - 27165:27165/tcp
      - 27166:27166/tcp
      - 21114:21114/tcp
      - 7787:7787/udp
      - 7788:7788/udp
      - 15000:15000/udp
      - 27165:27165/udp
      - 27166:27166/udp
      - 21114:21114/udp
